import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/payout_model.dart';
import '../models/transaction_model.dart';
import 'transaction_service.dart';

class PayoutService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final TransactionService _transactionService = TransactionService();

  // Request a payout
  Future<void> requestPayout(String userId, double amount, String paymentDetails) async {
    try {
      // Check balance first
      final balance = await _transactionService.getBalance(userId);
      if (balance < amount) {
        throw Exception('Insufficient balance');
      }

      final payout = PayoutModel(
        id: '', // Generated by Firestore
        userId: userId,
        amount: amount,
        status: PayoutStatus.pending,
        requestDate: DateTime.now(),
        paymentDetails: paymentDetails,
      );

      await _firestore.collection('payouts').add(payout.toMap());
    } catch (e) {
      print('Error requesting payout: $e');
      rethrow;
    }
  }

  // Get payouts for a user
  Stream<List<PayoutModel>> getPayouts(String userId) {
    return _firestore
        .collection('payouts')
        .where('userId', isEqualTo: userId)
        .orderBy('requestDate', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => PayoutModel.fromMap(doc.data(), doc.id))
          .toList();
    });
  }

  // Get all payouts (for Admin)
  Stream<List<PayoutModel>> getAllPayouts() {
    return _firestore
        .collection('payouts')
        .orderBy('requestDate', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => PayoutModel.fromMap(doc.data(), doc.id))
          .toList();
    });
  }

  // Update payout status (Admin only)
  Future<void> updatePayoutStatus(String payoutId, PayoutStatus status, {String? adminNote}) async {
    try {
      final docRef = _firestore.collection('payouts').doc(payoutId);
      
      await _firestore.runTransaction((transaction) async {
        final snapshot = await transaction.get(docRef);
        if (!snapshot.exists) {
          throw Exception('Payout request not found');
        }

        final payout = PayoutModel.fromMap(snapshot.data()!, snapshot.id);

        // If approving, deduct balance via transaction
        if (status == PayoutStatus.approved && payout.status != PayoutStatus.approved) {
           // Double check balance inside transaction to be safe
           // Note: getBalance is not transactional here, but we rely on the fact that
           // we are creating a debit transaction.
           // Ideally, we should check balance transactionally, but for now we assume
           // the admin checks are sufficient or we allow negative if race condition (rare).
           
           // Create debit transaction
           final debitTransaction = TransactionModel(
             id: '',
             userId: payout.userId,
             amount: payout.amount,
             type: TransactionType.debit,
             description: 'Payout Approved (Ref: $payoutId)',
             status: TransactionStatus.completed,
             referenceId: payoutId,
             createdAt: DateTime.now(),
           );
           
           // We can't use TransactionService.recordTransaction inside runTransaction directly
           // if it uses a different transaction context.
           // So we write directly to transactions collection.
           final transactionRef = _firestore.collection('transactions').doc();
           transaction.set(transactionRef, debitTransaction.toMap());
        }

        transaction.update(docRef, {
          'status': status.name,
          'processedDate': Timestamp.now(),
          'adminNote': adminNote,
        });
      });

    } catch (e) {
      print('Error updating payout status: $e');
      rethrow;
    }
  }
}
