import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import '../models/payout_model.dart';
import '../models/transaction_model.dart';
import 'transaction_service.dart';

class PayoutService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final TransactionService _transactionService = TransactionService();

  // Request a payout (withdrawal) or record a commission transfer (partner payment to admin)
  Future<void> requestPayout(String userId, double amount, String paymentDetails, 
      {PayoutType type = PayoutType.withdrawal, PayoutStatus status = PayoutStatus.pending}) async {
    try {
      if (type == PayoutType.withdrawal) {
        if (amount < 500) {
          throw Exception('Minimum withdrawal amount is ₹500');
        }

        // Check balance first
        final balance = await _transactionService.getBalance(userId);
        if (balance < amount) {
          throw Exception('Insufficient balance');
        }

        // Check for daily limit (max 2 requests in last 24 hours)
        final now = DateTime.now();
        final last24Hours = now.subtract(const Duration(hours: 24));
        
        final recentPayoutsOrEmpty = await _firestore
            .collection('payouts')
            .where('userId', isEqualTo: userId)
            .where('requestDate', isGreaterThan: Timestamp.fromDate(last24Hours))
            .where('type', isEqualTo: PayoutType.withdrawal.name)
            .get();
            
        if (recentPayoutsOrEmpty.docs.length >= 2) {
           throw Exception('You can only make 2 payout requests every 24 hours');
        }
      }

      final payout = PayoutModel(
        id: '', // Generated by Firestore
        userId: userId,
        amount: amount,
        status: status,
        type: type,
        requestDate: DateTime.now(),
        paymentDetails: paymentDetails,
      );

      await _firestore.collection('payouts').add(payout.toMap());
    } catch (e) {
      debugPrint('Error requesting payout: $e');
      rethrow;
    }
  }

  // Get payouts for a user
  Stream<List<PayoutModel>> getPayouts(String userId) {
    return _firestore
        .collection('payouts')
        .where('userId', isEqualTo: userId)
        .orderBy('requestDate', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => PayoutModel.fromMap(doc.data(), doc.id))
          .toList();
    });
  }

  // Get all payouts (for Admin)
  Stream<List<PayoutModel>> getAllPayouts() {
    return _firestore
        .collection('payouts')
        .orderBy('requestDate', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => PayoutModel.fromMap(doc.data(), doc.id))
          .toList();
    });
  }

  // Update payout status (Admin only)
  Future<void> updatePayoutStatus(String payoutId, PayoutStatus status, {String? adminNote}) async {
    try {
      final docRef = _firestore.collection('payouts').doc(payoutId);
      
      await _firestore.runTransaction((transaction) async {
        final snapshot = await transaction.get(docRef);
        if (!snapshot.exists) {
          throw Exception('Payout request not found');
        }

        final payout = PayoutModel.fromMap(snapshot.data()!, snapshot.id);

        if (status == PayoutStatus.approved && payout.status != PayoutStatus.approved) {
           final isWithdrawal = payout.type == PayoutType.withdrawal;
           
           // Create transaction record
           final tx = TransactionModel(
             id: '',
             userId: payout.userId,
             amount: payout.amount,
             type: isWithdrawal ? TransactionType.debit : TransactionType.credit,
             description: isWithdrawal 
                ? 'Payout Approved (Ref: $payoutId)' 
                : 'Commission Payment Approved (Ref: $payoutId)',
             status: TransactionStatus.completed,
             referenceId: payoutId,
             createdAt: DateTime.now(),
             metadata: {
                'sellerId': payout.userId,
                'type': payout.type.name,
             },
           );
           
           final transactionRef = _firestore.collection('transactions').doc();
           transaction.set(transactionRef, tx.toMap());
        }

        transaction.update(docRef, {
          'status': status.name,
          'processedDate': Timestamp.now(),
          'adminNote': adminNote,
        });
      });

    } catch (e) {
      debugPrint('Error updating payout status: $e');
      rethrow;
    }
  }
}
