// This file will be generated by FlutterFire CLI
// Run: flutterfire configure
//
// Placeholder for now - you must run flutterfire configure to generate actual config

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi3xdZ5LPfHU7MuZ6zdmCqp5t6Fd-P1aQ',
    appId: '1:110161971301:web:985cb712126f0ec89ede8c',
    messagingSenderId: '110161971301',
    projectId: 'bong-bazar-3659f',
    authDomain: 'bong-bazar-3659f.firebaseapp.com',
    databaseURL: 'https://bong-bazar-3659f-default-rtdb.firebaseio.com',
    storageBucket: 'bong-bazar-3659f.firebasestorage.app',
    measurementId: 'G-W6B150JE42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwTZrdVIP7sLoJzXq2KXJ7gatAbKS6yY',
    appId: '1:110161971301:android:1ca561a37bca76699ede8c',
    messagingSenderId: '110161971301',
    projectId: 'bong-bazar-3659f',
    databaseURL: 'https://bong-bazar-3659f-default-rtdb.firebaseio.com',
    storageBucket: 'bong-bazar-3659f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNeyw_5TtnGa9InuK7YuE1wC_tNjPy-m0',
    appId: '1:110161971301:ios:b048c547edde247e9ede8c',
    messagingSenderId: '110161971301',
    projectId: 'bong-bazar-3659f',
    databaseURL: 'https://bong-bazar-3659f-default-rtdb.firebaseio.com',
    storageBucket: 'bong-bazar-3659f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNeyw_5TtnGa9InuK7YuE1wC_tNjPy-m0',
    appId: '1:110161971301:ios:b048c547edde247e9ede8c',
    messagingSenderId: '110161971301',
    projectId: 'bong-bazar-3659f',
    databaseURL: 'https://bong-bazar-3659f-default-rtdb.firebaseio.com',
    storageBucket: 'bong-bazar-3659f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi3xdZ5LPfHU7MuZ6zdmCqp5t6Fd-P1aQ',
    appId: '1:110161971301:web:c7681f274adb53c89ede8c',
    messagingSenderId: '110161971301',
    projectId: 'bong-bazar-3659f',
    authDomain: 'bong-bazar-3659f.firebaseapp.com',
    databaseURL: 'https://bong-bazar-3659f-default-rtdb.firebaseio.com',
    storageBucket: 'bong-bazar-3659f.firebasestorage.app',
    measurementId: 'G-89K9RTPEV1',
  );
}
