class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'settings': 'Settings',
      'privacy_security': 'Privacy & Security',
      'return_policy': 'Return Policy',
      'about_us': 'About Us',
      'logout': 'Logout',
      'language': 'Language',
      'notifications': 'Notifications',
      'theme': 'Theme',
      'data_storage': 'Data & Storage',
      'payment_methods': 'Payment Methods',
      'addresses': 'Addresses',
      'app_version': 'App Version',
      'clear_cache': 'Clear Cache',
      'choose_language': 'Choose Language',
      'choose_theme': 'Choose Theme',
      'light': 'Light',
      'dark': 'Dark',
      'auto_system_default': 'Auto (System default)',
      'manage_cache_data': 'Manage cache and data',
      'manage_saved_cards': 'Manage saved cards',
      'manage_delivery_addresses': 'Manage delivery addresses',
      'storage_settings_coming_soon': 'Storage settings coming soon',
      'payment_settings_coming_soon': 'Payment settings coming soon',
      'cancel': 'Cancel',
      'on': 'On',
      'off': 'Off',
      'coming_soon': 'Coming soon',
      'cache_cleared': 'Cache cleared',
      'notifications_enabled': 'Notifications enabled',
      'notifications_disabled': 'Notifications disabled',
      'your_trust': 'Your trust is our deepest relationship.',
    },
    'hi': {
      'settings': 'सेटिंग्स',
      'privacy_security': 'गोपनीयता और सुरक्षा',
      'return_policy': 'वापसी नीति',
      'about_us': 'हमारे बारे में',
      'logout': 'लॉगआउट',
      'language': 'भाषा',
      'notifications': 'सूचनाएं',
      'theme': 'थीम',
      'data_storage': 'डेटा और स्टोरेज',
      'payment_methods': 'भुगतान के तरीके',
      'addresses': 'पते',
      'app_version': 'ऐप संस्करण',
      'clear_cache': 'कैश साफ़ करें',
      'choose_language': 'भाषा चुनें',
      'choose_theme': 'थीम चुनें',
      'light': 'लाइट',
      'dark': 'डार्क',
      'auto_system_default': 'ऑटो (सिस्टम डिफॉल्ट)',
      'manage_cache_data': 'कैश और डेटा प्रबंधित करें',
      'manage_saved_cards': 'सहेजे गए कार्ड प्रबंधित करें',
      'manage_delivery_addresses': 'डिलीवरी पते प्रबंधित करें',
      'storage_settings_coming_soon': 'स्टोरेज सेटिंग्स जल्द आ रही हैं',
      'payment_settings_coming_soon': 'भुगतान सेटिंग्स जल्द आ रही हैं',
      'cancel': 'रद्द करें',
      'on': 'चालू',
      'off': 'बंद',
      'coming_soon': 'जल्द आ रहा है',
      'cache_cleared': 'कैश साफ़ किया गया',
      'notifications_enabled': 'सूचनाएं सक्षम',
      'notifications_disabled': 'सूचनाएं अक्षम',
      'your_trust': 'आपका विश्वास, हमारा सबसे गहरा रिश्ता है।',
    },
    'bn': {
      'settings': 'সেটিংস',
      'privacy_security': 'গোপনীয়তা এবং নিরাপত্তা',
      'return_policy': 'ফেরত নীতি',
      'about_us': 'আমাদের সম্পর্কে',
      'logout': 'লগআউট',
      'language': 'ভাষা',
      'notifications': 'বিজ্ঞপ্তি',
      'theme': 'থিম',
      'data_storage': 'ডেটা এবং স্টোরেজ',
      'payment_methods': 'পেমেন্ট পদ্ধতি',
      'addresses': 'ঠিকানা',
      'app_version': 'অ্যাপ সংস্করণ',
      'clear_cache': 'ক্যাশ পরিষ্কার করুন',
      'choose_language': 'ভাষা চয়ন করুন',
      'choose_theme': 'থিম চয়ন করুন',
      'light': 'লাইট',
      'dark': 'ডার্ক',
      'auto_system_default': 'অটো (সিস্টেম ডিফল্ট)',
      'manage_cache_data': 'ক্যাশ এবং ডেটা পরিচালনা করুন',
      'manage_saved_cards': 'সংরক্ষিত কার্ড পরিচালনা করুন',
      'manage_delivery_addresses': 'ডেলিভারি ঠিকানা পরিচালনা করুন',
      'storage_settings_coming_soon': 'স্টোরেজ সেটিংস শীঘ্রই আসছে',
      'payment_settings_coming_soon': 'পেমেন্ট সেটিংস শীঘ্রই আসছে',
      'cancel': 'বাতিল করুন',
      'on': 'চালু',
      'off': 'বন্ধ',
      'coming_soon': 'শীঘ্রই আসছে',
      'cache_cleared': 'ক্যাশ পরিষ্কার করা হয়েছে',
      'notifications_enabled': 'বিজ্ঞপ্তি সক্ষম',
      'notifications_disabled': 'বিজ্ঞপ্তি অক্ষম',
      'your_trust': 'আপনার বিশ্বাস আমাদের গভীরতম সম্পর্ক।',
    },
  };

  static String get(String key, String langCode) {
    if (!_strings.containsKey(langCode)) {
      langCode = 'en';
    }
    return _strings[langCode]?[key] ?? _strings['en']?[key] ?? key;
  }
}
